---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 741373270419640320-CFcq9yJUa6YF1bxWbjQRHMK1cvvEupK
:access_token_secret: n5shfHxNgZa01sSqd3Ao9SLfT2PWkS4rwX7KA70j5wj4u
